[package]
name = "srs-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
pico-args = "0.5.0"
rusqlite = {version = "0.35.0", features = ["bundled"]}
time = {version = "0.3.41", features = ["local-offset"]}

[profile.release]
lto = true
codegen-units = 1
strip = "debuginfo"
