[package]
name = "srs-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.56"
chrono = "0.4.19"
clap = {version = "3.1.6", features = ["derive"]}
dialoguer = "0.10.0"
rusqlite = {version = "0.27.0", features = ["bundled"]}
skim = "0.9.4"
